### ISSUE TITLE
Picture

### ISSUE THREAD

**Issue by bolkedebruin** [bolkedebruin/erhv-lovelace#1]
<img width="485" alt="Screenshot 2023-12-06 at 22 34 20" src="https://github.com/bolkedebruin/erhv-lovelace/assets/4282712/38bfd115-2c45-429f-a17c-27abbc606356">

**Comment by jameswilso** [comment]
@bolkedebruin how did you solver this issue - I have something similar and assume I've got two entities the wrong way round

**Comment by bolkedebruin** [comment]
What issue exactly?
