### ISSUE TITLE
The custom card requires an entity but I cant figure out what it should be

### ISSUE THREAD

**Issue by DTekNOdev** [bolkedebruin/erhv-lovelace#2]
![image](https://github.com/bolkedebruin/erhv-lovelace/assets/8317651/5a6381f1-f3e7-4572-9daa-282c9d08dfac)

I tried to use this card but it (apparently) requires an entity to be defined, but which one?

**Comment by bolkedebruin** [comment]
By accident I've omitted the entity setting from the readme. Just add

```yaml
entity: climate.ca350_climate
```

in your case this should probably be `climate.flexit_nordic`.

**Comment by DTekNOdev** [comment]
Adding an entity like this gave me an error "unknown entity". However in the latest version it does not, so this issue can be closed. I have other issues though, see additional reports.
